services:
  hikvision-webhook:
    build: .
    container_name: hikvision-webhook
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=${PORT:-8080}
      - ALLOW_IPS=${ALLOW_IPS}
      - LOG_DIR=/data/logs
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-admin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-password123}
      - MINIO_BUCKET=${MINIO_BUCKET:-hikvision-images}
    volumes:
      - ./data:/data
    depends_on:
      - minio
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-password123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_data:
